language: java

sudo: false

cache:
  directories:
    - $HOME/.m2

env:
  - PROJECT_DIR=adstats-java
  #- PROJECT_DIR=adstats-kotlin

script: "cd $PROJECT_DIR && mvn cobertura:cobertura"

after_success:
- bash <(curl -s https://codecov.io/bash)

jdk:
  - oraclejdk8
